version: '3.5'

services:

  backend:
    image: modified_back
    build: .
    expose:
      - 8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db

  frontend:
    image: modified_front
    build: .
    expose:
      - 5000

  redis:
    image: redis
    build: .
    expose:
      - 6379

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    container_name: db_example
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  database: