version: '3.5'

services: 

  backend:
    image: modified_back
    build: .
    ports: 
      - 8080:8080
    environment: 
      - REDIS_HOST=redis
  
  frontend:
    image: modified_front
    build: .
    ports: 
      - 5000:5000
  
  redis:
    image: redis
    build: .
    ports: 
      - 6379:6379